### ISSUE TITLE
Refactor WebContext.setSessionStore

### ISSUE THREAD

**Issue by millross** [pac4j/pac4j#873] opened 2017-03-27 07:37 UTC
Since it makes no sense for the session store associated with a WebContext instance to change during the lifetime of the WebContext, there should not be a setter for this. All it does is create API noise, and the only sensible implementation is an UnsupportedOperationException.

It's reasonable (and actually should be enforced) that the SessionStore should be set during the construction of the WebContext instance and not be changed during the lifetime of the instance. So we should deprecate this method in 2.0 and remove it in 3.0.

I'm happy to hear any use-cases where we think we should change the SessionStore during the lifetime of the WebContext and be persuaded that I'm wrong.

**Comment by leleuj** [comment] 2017-03-27 09:18
You raise a good point. The `setSessionStore` method is used only two times: in the web context constructor and in the `DefaultCasLogoutHandler`.
The first use case is not an issue.
The second use case is in the CAS logout: https://github.com/pac4j/pac4j/blob/master/pac4j-cas/src/main/java/org/pac4j/cas/logout/DefaultCasLogoutHandler.java#L111

I need to investigate a little more on this to find back the right reasons.

**Comment by millross** [comment] 2017-03-27 09:32
Looking at DefaultCasLogoutHandler is there any need to retain the WebContext after the end of the handling? I think you're using it just as a means to destroy the session. 

I think a more appropriate approach is that SessionStore should offer a destroySession mechanism which can destroy any session based on sessionId rather than switching the current WebContext to use that session. 

Just to be clear, in vert.x, we will not be able to switch sessions (and actually in general I would discourage code which attaches a different user session to the current caller), but we will be able to destroy a session based on session id. The setting of the session store feels like a way to try and avoid having to implement "destroySession(sessionId)" in session store to me.

**Comment by leleuj** [comment] 2017-03-28 16:46
The `setSessionStore` is a new method in the 2.0.0 version so if we remove it, we don't need to deprecate it first.
I need to check the way the logout is performed and if it's really necessary or if we can do better.

**Comment by millross** [comment] 2017-03-28 16:56
Understood, but equally maybe now (building up to release) isn't the time for radical change in which case deprecation and replacement of the implementation of session removal for CAS can be done during the 2.x.x lifecycle. It just means that we can't support that aspect for vertx-pac4j.

**Comment by leleuj** [comment] 2017-04-03 10:28
Additional Jez's proposal: "Can I suggest that we offer a destroySessionById() method on SessionStore? I could certainly implement that in vertx-web. What I can’t do is attach someone else’s session to the WebContext to destroy it, which is the current basis of the cas logout implementation."

**Comment by leleuj** [comment] 2017-04-03 12:21
Deprecate in 2.0 and rework in 3.0.

**Comment by millross** [comment] 2017-04-03 12:38
I'll try and add some suggestions here to minimise rework :) I have a couple of ideas that might become tangible when I've worked on a vertx cas logout implementation during the lifecycle of pac4j 2.x.

**Comment by victornoel** [comment] 2017-04-16 10:09
I'm really curious as to why it is a good idea to deprecate a method that didn't exist in the previous version... I understand that it is going to mean some work but don't you think it will be even worse when it is going to be deprecated in v3? IMHO we should remove it once and for all. Anyway, if I understood right a RC3 is planned, so it is ok to continue changes like this!

**Comment by leleuj** [comment] 2017-04-17 13:45
I understand your concern.

The timeline for the final release is May so we should stop making big changes and RC3 should be the last RC before the final release.
Though, we have added the `setSessionStore` method which is the foundation for back-channel logout (implemented by CAS). Eventually, it does not fit very well for Vert.x. Changing that method would require some substantive work.
So I have the feeling (with Jez) that it's too late to start reworking that. So let's add it as `deprecated` to warn users it's just an intermediate step and use a workaround in Vert.x

**Comment by millross** [comment] 2017-04-17 14:57
Agree with @leleuj - to remove this method would mean rewriting the back-channel logout. Ultimately IMO we should rewrite back-channel logout more cleanly (it isn't really clean to switch between sessions to trigger a logout - more correctly the session store should, given a session id, know how to clean out that session). In the more general case, changing session stores might imply something bigger than just switching sessions, which would be worse.

So for me, we should deprecate this to discourage using it during release of the 3.0 stream, and during 3.0 remove it altogether, rather than forcing a rewrite of back-channel logout. I'm working on the vert.x back-channel logout (which cannot use the existing mechanism) and will use this to suggest changes to the session store API which will hopefully make it possible to go back to all implementations being able to use a default back-channel logout against a general SessionStore API.

**Comment by millross** [comment] 2017-04-17 14:58
And yes, we're past the time for big changes and API breaks, given release is due in a couple of weeks.

**Comment by victornoel** [comment] 2017-04-17 15:00
Thanks for your explanations :) I wasn't even aware of this back-channel logout... is there some more doc on what it is? I wonder if I have anything to do for jax-rs-pac4j...

**Comment by leleuj** [comment] 2017-04-17 18:25
The back-channel logout is when the identity server directly calls the application providing some identifier to be able to destroy the user's session (no cookie, thus no session affinity). While the front-channel logout is when the identity server makes the user's browser calls the application.

This is the power of pac4j: given you have implemented the `setSessionStore` method, it should work out-of-the-box for jax-rs-pac4j.

**Comment by victornoel** [comment] 2017-04-18 07:17
@leleuj ok :) if you get the time, could you do a quick review of my implementations of webcontext and sessionstore in jax-rs-pac4j to be sure there is no shortcomings? :)

**Comment by leleuj** [comment] 2017-04-18 09:59
I took a look at the `JaxRsContext` class and I have three comments:

- what is `Response.ok()`? I find the `getAbortBuilder()`  method surprising

- I'm surprised by this also: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java#L170

- I see a remaining `TODO` in the `getRequestContent` method.

**Comment by victornoel** [comment] 2017-04-18 10:26
> what is Response.ok()? I find the getAbortBuilder() method surprising

It's how JAX-RS work: if you want to answer something from a filter, you need to abort the current request with a custom response. The `abortResponse` variable is just there to let pac4j build this response via its `WebContext` methods and at the end of pac4j execution in the filter, my code will use this object to tell JAX-RS to abort the request and answer with pac4j's response (https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/filters/JaxRsHttpActionAdapter.java).
Response.ok() is a 200 response, it will be the default if pac4j tries to use the `HttpActionAdapter` even though it didn't set any response. This should not happen, but who knows? better safe than sorry… I could put something else maybe there…

> I'm surprised by this also: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java#L170

Why? `readAndResetEntityStream` expects that the lambda returns something but I don't have anything to return, since lambda can't be `void` the normal way is usually to use `Void` and return `null`… it is purely technical, this null is used nowhere.

> I see a remaining TODO in the getRequestContent method.

Yep, is it solved in the J2EContext? Basically the line-termination characters seem to be skipped…
Anyway, I remember I was the origin of adding this method, but in the end, I'm not really convinced by its "raison d'être" :) it is too much framework AND user code specific to be done in pac4j, it's a bit out of scope of pac4j I think… not sure :)

**Comment by leleuj** [comment] 2017-04-18 14:07
2) You add all form parameters to the parameters map (`form.asMap().forEach(parameters::addAll);`): why return `null` and not the `parameters` map?

**Comment by victornoel** [comment] 2017-04-18 14:12
Because the return value wouldn't be used anyway… I think you are misunderstanding what `readAndResetEntityStream` is actually doing with the returned value… 

The code of `extractedParameters` put the parameters in the parameters object, which is returned every time at the end of the method.

**Comment by leleuj** [comment] 2017-04-18 14:18
Ok, I see now, the `null` is not returned by `extractedParameters` but by the function passed to `readAndResetEntityStream`.

**Closed** 2017-09-13 03:17 UTC
Labels: Improvement

**Comment by ciekawy** [comment] 2019-05-01 00:13
out of curiosity - I am trying to make the `@Pac4JSecurity` require authentication from all the clients. I tried to throw 401 `HttpAction` yet doing so in either overridden `DirectClientV2.retrieveCredentials` on `null` credentials OR in `Authorizer` but facing mentioned above `Response.ok()` not equal to `HttpAction` 401 code...

is there another way to achieve the goal of requiring all the clients to return non null credentials?

**Comment by leleuj** [comment] 2019-05-01 11:07
I'm not sure to follow you: you want to authenticate for all direct clients at the same time?

1) Turn on the `multiprofile` support at the security level
2) Create an authorizer which checks that you have as many profiles as the direct clients you have configured.

**Comment by ciekawy** [comment] 2019-05-01 18:17
Thanks for responding. Yep I want to authenticate for all direct clients and return 401 otherwise. That was I was trying to do but the was struggling with returning 401 (as `Authorizer.isAuthorized()` is returning 403 on false).

Finally yesterday got this to work and return 401 (which is by design expectation to enforece re-authentication in some cases) by throwing `HttpAction.unauthorized()` in case of missing credentials from direct clients. As I see in the new version it will be `UnathorizedAction`, yet we're on the 1.9.x as for now.

**Comment by leleuj** [comment] 2019-05-02 05:41
Yes, it's 403 by default, but you can force anything by throwing the appropriate `HttpAction`.
